# Generated by Django 5.2.14 on 2026-05-25 02:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ingestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmissionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("SCOPE_1", "Scope 1"),
                            ("SCOPE_2", "Scope 2"),
                            ("SCOPE_3", "Scope 3"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FUEL", "Fuel"),
                            ("ELECTRICITY", "Electricity"),
                            ("FLIGHT", "Flight"),
                            ("HOTEL", "Hotel"),
                            ("GROUND_TRANSPORT", "Ground Transport"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subcategory", models.CharField(max_length=100)),
                ("raw_quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                ("raw_unit", models.CharField(max_length=50)),
                ("raw_date", models.CharField(max_length=50)),
                ("activity_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("vendor", models.CharField(blank=True, max_length=255)),
                ("origin_code", models.CharField(blank=True, max_length=10)),
                ("destination_code", models.CharField(blank=True, max_length=10)),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("travel_class", models.CharField(blank=True, max_length=50)),
                ("hotel_nights", models.IntegerField(blank=True, null=True)),
                (
                    "normalized_quantity_kgco2e",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                (
                    "emission_factor",
                    models.DecimalField(decimal_places=6, max_digits=15),
                ),
                ("emission_factor_source", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("FLAGGED", "Flagged"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("flag_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_suspicious", models.BooleanField(default=False)),
                ("suspicious_reason", models.TextField(blank=True)),
                (
                    "normalization_version",
                    models.CharField(default="DEFRA_2023_v1", max_length=100),
                ),
                ("row_number", models.IntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emission_records",
                        to="core.company",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emission_records",
                        to="ingestion.datasource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("EDITED", "Edited"),
                            ("APPROVED", "Approved"),
                            ("FLAGGED", "Flagged"),
                            ("REJECTED", "Rejected"),
                            ("LOCKED", "Locked"),
                        ],
                        max_length=50,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("old_value", models.JSONField(blank=True, default=dict)),
                ("new_value", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="core.company",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="review.emissionrecord",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["company", "status"], name="review_emis_company_24f38c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(fields=["scope"], name="review_emis_scope_04bfd7_idx"),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["activity_date"], name="review_emis_activit_f97f1e_idx"
            ),
        ),
    ]
