# Generated by Django 5.2.14 on 2026-05-25 02:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP"),
                            ("UTILITY", "Utility"),
                            ("TRAVEL", "Travel"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "ingestion_mode",
                    models.CharField(
                        choices=[
                            ("FILE_UPLOAD", "File Upload"),
                            ("API_PULL", "API Pull"),
                        ],
                        default="FILE_UPLOAD",
                        max_length=50,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_hash", models.CharField(max_length=64)),
                ("raw_file", models.FileField(upload_to="datasources/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("PARTIAL", "Partial"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("parsed_rows", models.IntegerField(default=0)),
                ("failed_rows", models.IntegerField(default=0)),
                ("error_log", models.JSONField(blank=True, default=list)),
                ("reporting_period_start", models.DateField(blank=True, null=True)),
                ("reporting_period_end", models.DateField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("parser_version", models.CharField(default="v1", max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sources",
                        to="core.company",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParseError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.IntegerField()),
                ("raw_row", models.TextField()),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("MISSING_FIELD", "Missing Field"),
                            ("BAD_DATE", "Bad Date"),
                            ("UNKNOWN_UNIT", "Unknown Unit"),
                            ("UNKNOWN_MATERIAL", "Unknown Material"),
                            ("BAD_FORMAT", "Bad Format"),
                        ],
                        max_length=50,
                    ),
                ),
                ("error_message", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parse_errors",
                        to="core.company",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parse_errors",
                        to="ingestion.datasource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
